resolver: nightly-2017-11-15
packages:
  - './'
extra-deps:
  - megaparsec-6.2.0
  - htoml-megaparsec-1.0.1.11
  - composition-prelude-0.1.1.0
flags:
  tomlcheck:
    optimize: true
extra-package-dbs: []
